---
- name: Create remote_tmp directory
  file:
    path: /root/.ansible/tmp
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Add Apt signing key from official docker repo
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: add docker official repository for Debian Stretch
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
    state: present
  notify:
    - update apt package index
